module.exports.LINE_WIDTH_PERCENT = 0.07;
module.exports.SC_PERCENT = 0.4;
module.exports.MC_PERCENT = 0.9;
module.exports.BC_PERCENT = 1.2;
module.exports.FC_PERCENT = 1.1;
module.exports.COLOR_CONFIG = {
	DARK: {
		BASE_COLOR_INTERVAL_MIN: 50,
		BASE_COLOR_INTERVAL_MAX: 120,
		BASE_COLOR_SECOND_OFFSET_MIN: 40,
		BASE_COLOR_SECOND_OFFSET_MAX: 100,
		BASE_COLOR_THIRD_OFFSET_MIN: 100,
		SECOND_COLOR_OFFSET: 70,
	},
	LIGHT: {
		BASE_COLOR_INTERVAL_MIN: 180,
		BASE_COLOR_INTERVAL_MAX: 255,
		BASE_COLOR_SECOND_OFFSET_MIN: 60,
		BASE_COLOR_SECOND_OFFSET_MAX: 100,
		BASE_COLOR_THIRD_OFFSET_MIN: 100,
		SECOND_COLOR_OFFSET: -70,
	},
};
